In [1]:
import pandas as pd

path = "/kaggle/input/datasets/samartalwar/sleep-debt-and-screen-time-late-night-phone-habits/bedtime_screentime_sleep_debt.csv"

df = pd.read_csv(path)

df.head()

,user_id,age,gender,occupation_type,chronotype,bedtime_phone_minutes,primary_bedtime_app,screen_brightness_pct,blue_light_filter_active,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,deep_sleep_pct,rem_sleep_pct,morning_alarm_snoozes,next_day_fatigue_score,sleep_debt_category
0,USR-00001,29,Female,Healthcare / Shift Worker,Intermediate,179,Instagram / Reddit,54,1,0,21,84.4,3.20,23.5,22.2,7,10.0,Severe Sleep Debt
1,USR-00002,58,Female,Student,Intermediate,163,YouTube,76,1,92,72,86.7,4.06,18.0,21.5,7,10.0,Severe Sleep Debt
2,USR-00003,41,Female,Healthcare / Shift Worker,Night Owl,100,TikTok / Reels,59,0,45,23,70.5,3.20,18.1,20.5,7,10.0,Severe Sleep Debt
3,USR-00004,36,Non-Binary,Remote Tech,Intermediate,34,YouTube,52,0,97,49,38.1,6.99,21.6,22.4,1,1.7,Mild Deficit
4,USR-00005,23,Female,Healthcare / Shift Worker,Intermediate,27,TikTok / Reels,82,1,0,38,32.3,4.58,24.1,22.8,4,5.3,Moderate Debt

In [2]:
df.describe(include="all")

,user_id,age,gender,occupation_type,chronotype,bedtime_phone_minutes,primary_bedtime_app,screen_brightness_pct,blue_light_filter_active,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,deep_sleep_pct,rem_sleep_pct,morning_alarm_snoozes,next_day_fatigue_score,sleep_debt_category
count,8500,8500.000000,8500,8500,8500,8500.000000,8500,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500
unique,8500,NaN,3,5,3,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
top,USR-08500,NaN,Female,Corporate 9-to-5,Intermediate,NaN,TikTok / Reels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate Debt
freq,1,NaN,4347,2838,3880,NaN,2198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4462
mean,NaN,34.355647,NaN,NaN,NaN,59.250000,NaN,55.153882,0.467765,33.222471,35.701412,40.671471,6.266209,21.735741,19.105859,2.766000,3.794671,NaN
std,NaN,11.584259,NaN,NaN,NaN,36.931991,NaN,19.850550,0.498989,51.935645,20.819390,17.444914,1.446258,3.069377,2.546459,1.695407,2.685153,NaN
min,NaN,18.000000,NaN,NaN,NaN,1.000000,NaN,10.000000,0.000000,0.000000,0.000000,6.000000,3.200000,8.100000,9.600000,0.000000,1.000000,NaN
25%,NaN,25.000000,NaN,NaN,NaN,31.000000,NaN,42.000000,0.000000,0.000000,21.000000,28.200000,5.240000,19.700000,17.400000,2.000000,1.100000,NaN
50%,NaN,32.000000,NaN,NaN,NaN,51.000000,NaN,55.000000,0.000000,0.000000,35.000000,37.600000,6.330000,21.900000,19.100000,3.000000,3.200000,NaN
75%,NaN,42.000000,NaN,NaN,NaN,79.000000,NaN,69.000000,1.000000,55.000000,50.000000,49.700000,7.350000,23.900000,20.800000,4.000000,5.600000,NaN
max,NaN,65.000000,NaN,NaN,NaN,180.000000,NaN,100.000000,1.000000,250.000000,112.000000,123.300000,9.800000,28.000000,27.000000,7.000000,10.000000,NaN

In [3]:
print(df.shape)
print(df.columns.tolist())
df.info()

(8500, 18)
['user_id', 'age', 'gender', 'occupation_type', 'chronotype', 'bedtime_phone_minutes', 'primary_bedtime_app', 'screen_brightness_pct', 'blue_light_filter_active', 'caffeine_post_5pm_mg', 'physical_activity_min', 'sleep_latency_min', 'total_sleep_hours', 'deep_sleep_pct', 'rem_sleep_pct', 'morning_alarm_snoozes', 'next_day_fatigue_score', 'sleep_debt_category']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   8500 non-null   object
 1   age                       8500 non-null   int64
 2   gender                    8500 non-null   object
 3   occupation_type           8500 non-null   object
 4   chronotype                8500 non-null   object
 5   bedtime_phone_minutes     8500 non-null   int64
 6   primary_bedtime_app       8500 non-null   object
 7   screen_brightness_pct     8500 non-null   int64
 8   blue_light_filter_active  8500 non-null   int64
 9   caffeine_post_5pm_mg      8500 non-null   int64
 10  physical_activity_min     8500 non-null   int64
 11  sleep_latency_min         8500 non-null   float64
 12  total_sleep_hours         8500 non-null   float64
 13  deep_sleep_pct            8500 non-null   float64
 14  rem_sleep_pct             8500 non-null   float64
 15  morning_alarm_snoozes     8500 non-null   int64
 16  next_day_fatigue_score    8500 non-null   float64
 17  sleep_debt_category       8500 non-null   object
dtypes: float64(5), int64(7), object(6)
memory usage: 1.2+ MB

In [4]:
df["sleep_debt_category"].value_counts()

sleep_debt_category
Moderate Debt        4462
Mild Deficit         2004
Optimal Recovery     1387
Severe Sleep Debt     647
Name: count, dtype: int64

In [5]:
for col in [
    "gender",
    "occupation_type",
    "chronotype",
    "primary_bedtime_app",
    "sleep_debt_category"
]:
    print("\n", col)
    print(df[col].value_counts())

 gender
gender
Female        4347
Male          3905
Non-Binary     248
Name: count, dtype: int64

 occupation_type
occupation_type
Corporate 9-to-5             2838
Remote Tech                  2142
Student                      1622
Healthcare / Shift Worker     997
Freelance / Creative          901
Name: count, dtype: int64

 chronotype
chronotype
Intermediate    3880
Night Owl       2455
Morning Lark    2165
Name: count, dtype: int64

 primary_bedtime_app
primary_bedtime_app
TikTok / Reels              2198
YouTube                     1928
Instagram / Reddit          1630
Streaming (Netflix/Hulu)    1301
Messaging / Chat             847
News / Reading               596
Name: count, dtype: int64

 sleep_debt_category
sleep_debt_category
Moderate Debt        4462
Mild Deficit         2004
Optimal Recovery     1387
Severe Sleep Debt     647
Name: count, dtype: int64

In [6]:
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

corr = df[numeric_cols].corr()

corr.round(2)

,age,bedtime_phone_minutes,screen_brightness_pct,blue_light_filter_active,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,deep_sleep_pct,rem_sleep_pct,morning_alarm_snoozes,next_day_fatigue_score
age,1.00,-0.02,-0.01,0.00,-0.01,-0.01,-0.06,0.02,0.01,0.07,-0.03,-0.03
bedtime_phone_minutes,-0.02,1.00,0.00,0.00,-0.01,-0.01,0.86,-0.55,-0.26,-0.01,0.65,0.71
screen_brightness_pct,-0.01,0.00,1.00,0.01,0.00,0.00,0.09,-0.03,-0.15,0.00,0.05,0.09
blue_light_filter_active,0.00,0.00,0.01,1.00,-0.00,0.00,-0.06,0.04,0.11,0.00,-0.04,-0.08
caffeine_post_5pm_mg,-0.01,-0.01,0.00,-0.00,1.00,-0.00,0.20,-0.04,-0.34,-0.42,0.09,0.18
physical_activity_min,-0.01,-0.01,0.00,0.00,-0.00,1.00,-0.01,0.00,0.33,-0.00,-0.01,-0.03
sleep_latency_min,-0.06,0.86,0.09,-0.06,0.20,-0.01,1.00,-0.53,-0.33,-0.16,0.68,0.74
total_sleep_hours,0.02,-0.55,-0.03,0.04,-0.04,0.00,-0.53,1.00,0.18,0.03,-0.83,-0.88
deep_sleep_pct,0.01,-0.26,-0.15,0.11,-0.34,0.33,-0.33,0.18,1.00,0.17,-0.23,-0.34
rem_sleep_pct,0.07,-0.01,0.00,0.00,-0.42,-0.00,-0.16,0.03,0.17,1.00,-0.08,-0.11
morning_alarm_snoozes,-0.03,0.65,0.05,-0.04,0.09,-0.01,0.68,-0.83,-0.23,-0.08,1.00,0.88
next_day_fatigue_score,-0.03,0.71,0.09,-0.08,0.18,-0.03,0.74,-0.88,-0.34,-0.11,0.88,1.00

In [7]:
categorical_cols = [
    "gender",
    "occupation_type",
    "chronotype",
    "primary_bedtime_app"
]

for col in categorical_cols:
    print(f"\n=== {col} ===")
    display(
        pd.crosstab(
            df[col],
            df["sleep_debt_category"],
            normalize="index"
        ).round(3)
    )

=== gender ===

sleep_debt_category,Mild Deficit,Moderate Debt,Optimal Recovery,Severe Sleep Debt
gender,,,,
Female,0.234,0.527,0.163,0.076
Male,0.237,0.526,0.162,0.075
Non-Binary,0.254,0.464,0.190,0.093

=== occupation_type ===

sleep_debt_category,Mild Deficit,Moderate Debt,Optimal Recovery,Severe Sleep Debt
occupation_type,,,,
Corporate 9-to-5,0.254,0.494,0.187,0.064
Freelance / Creative,0.260,0.509,0.162,0.069
Healthcare / Shift Worker,0.087,0.714,0.016,0.183
Remote Tech,0.249,0.509,0.184,0.057
Student,0.264,0.491,0.185,0.060

=== chronotype ===

sleep_debt_category,Mild Deficit,Moderate Debt,Optimal Recovery,Severe Sleep Debt
chronotype,,,,
Intermediate,0.320,0.501,0.120,0.059
Morning Lark,0.307,0.244,0.424,0.026
Night Owl,0.040,0.810,0.002,0.148

=== primary_bedtime_app ===

sleep_debt_category,Mild Deficit,Moderate Debt,Optimal Recovery,Severe Sleep Debt
primary_bedtime_app,,,,
Instagram / Reddit,0.235,0.532,0.156,0.077
Messaging / Chat,0.244,0.516,0.174,0.066
News / Reading,0.263,0.535,0.161,0.040
Streaming (Netflix/Hulu),0.240,0.528,0.176,0.056
TikTok / Reels,0.222,0.519,0.151,0.108
YouTube,0.238,0.524,0.170,0.068

In [8]:
df.groupby("chronotype")[
    [
        "bedtime_phone_minutes",
        "sleep_latency_min",
        "total_sleep_hours",
        "next_day_fatigue_score"
    ]
].mean().round(2)

,bedtime_phone_minutes,sleep_latency_min,total_sleep_hours,next_day_fatigue_score
chronotype,,,,
Intermediate,59.57,40.83,6.44,3.48
Morning Lark,59.75,40.90,7.38,2.53
Night Owl,58.31,40.22,5.01,5.40

In [9]:
df.groupby("occupation_type")[
    [
        "bedtime_phone_minutes",
        "caffeine_post_5pm_mg",
        "physical_activity_min",
        "sleep_latency_min",
        "total_sleep_hours",
        "next_day_fatigue_score"
    ]
].mean().round(2)

,bedtime_phone_minutes,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,next_day_fatigue_score
occupation_type,,,,,,
Corporate 9-to-5,59.07,32.79,35.30,40.83,6.43,3.57
Freelance / Creative,60.04,34.65,37.34,41.27,6.38,3.68
Healthcare / Shift Worker,59.30,33.72,35.45,40.96,5.02,5.54
Remote Tech,59.40,33.73,35.61,40.43,6.45,3.54
Student,58.89,32.21,35.77,40.19,6.45,3.51

In [10]:
df.groupby("primary_bedtime_app")[
    [
        "bedtime_phone_minutes",
        "sleep_latency_min",
        "total_sleep_hours",
        "next_day_fatigue_score"
    ]
].mean().round(2)

,bedtime_phone_minutes,sleep_latency_min,total_sleep_hours,next_day_fatigue_score
primary_bedtime_app,,,,
Instagram / Reddit,60.86,42.52,6.21,3.94
Messaging / Chat,59.46,38.31,6.33,3.59
News / Reading,60.09,33.21,6.38,3.33
Streaming (Netflix/Hulu),57.11,36.39,6.36,3.45
TikTok / Reels,59.85,46.15,6.17,4.16
YouTube,58.29,39.09,6.30,3.72

In [11]:
features = [
    "age",
    "gender",
    "occupation_type",
    "chronotype",
    "bedtime_phone_minutes",
    "primary_bedtime_app",
    "screen_brightness_pct",
    "blue_light_filter_active",
    "caffeine_post_5pm_mg",
    "physical_activity_min"
]

In [12]:
exclude = [
    "user_id",
    "sleep_debt_category",

    # Sleep outcomes / likely leakage
    "sleep_latency_min",
    "total_sleep_hours",
    "deep_sleep_pct",
    "rem_sleep_pct",
    "morning_alarm_snoozes",
    "next_day_fatigue_score"
]

In [13]:
target = "sleep_debt_category"

features = [
    "age",
    "gender",
    "occupation_type",
    "chronotype",
    "bedtime_phone_minutes",
    "primary_bedtime_app",
    "screen_brightness_pct",
    "blue_light_filter_active",
    "caffeine_post_5pm_mg",
    "physical_activity_min"
]

X = df[features]
y = df[target]

In [14]:
categorical_features = [
    "gender",
    "occupation_type",
    "chronotype",
    "primary_bedtime_app"
]

In [15]:
numeric_features = [
    "age",
    "bedtime_phone_minutes",
    "screen_brightness_pct",
    "blue_light_filter_active",
    "caffeine_post_5pm_mg",
    "physical_activity_min"
]

In [16]:
df.groupby("sleep_debt_category")["total_sleep_hours"].agg(
    ["min", "max", "mean", "median", "std"]
).round(2)

                      min   max  mean  median   std
sleep_debt_category
Mild Deficit         6.75  7.74  7.23    7.21  0.28
Moderate Debt        3.20  6.74  5.55    5.66  0.81
Optimal Recovery     7.75  9.80  8.35    8.23  0.48
Severe Sleep Debt    3.20  5.38  3.76    3.59  0.58